// Seeds sample workouts once per install. Deleting a sample does not bring it back.

import { Preferences } from '@capacitor/preferences';
import { hasWorkout, saveWorkout } from '../db/workouts.js';
import { buildWorkout } from '../services/workoutService.js';
import { CITY2SURF_SAMPLE_ID, generateCalibratedCity2Surf } from './city2surf.js';

const FLAG = 'seed.city2surf2026';

export async function seedDefaultWorkouts() {
  try {
    const { value } = await Preferences.get({ key: FLAG });
    if (value) return false;
    if (!(await hasWorkout(CITY2SURF_SAMPLE_ID))) {
      const { text } = generateCalibratedCity2Surf();
      const { workout, track } = buildWorkout(text, CITY2SURF_SAMPLE_ID);
      workout.name = 'City2Surf 2026';
      workout.notes = 'Sample workout: Sydney City2Surf, Hyde Park to Bondi Beach via Heartbreak Hill, averaging 6:18 /km. Generated by Locale from the course map; not a real recording.';
      await saveWorkout(workout, track, text);
    }
    await Preferences.set({ key: FLAG, value: '1' });
    return true;
  } catch (e) {
    console.error('Seeding sample workouts failed', e);
    return false;
  }
}
