// Seeds sample workouts once per install. Deleting a sample does not bring it back.

import { Preferences } from '@capacitor/preferences';
import { getWorkout, saveWorkout } from '../db/workouts.js';
import { buildWorkout } from '../services/workoutService.js';
import { CITY2SURF_SAMPLE_ID, generateCalibratedCity2Surf } from './city2surf.js';

const FLAG_V1 = 'seed.city2surf2026';
/** v2 adds simulated heart rate. Existing samples are upgraded in place; deleted ones stay deleted. */
const FLAG_V2 = 'seed.city2surf2026.hr';

export async function seedDefaultWorkouts() {
  try {
    if ((await Preferences.get({ key: FLAG_V2 })).value) return false;
    const seededBefore = Boolean((await Preferences.get({ key: FLAG_V1 })).value);
    const existing = await getWorkout(CITY2SURF_SAMPLE_ID);
    if (existing || !seededBefore) {
      const { text } = generateCalibratedCity2Surf();
      const { workout, track } = buildWorkout(text, CITY2SURF_SAMPLE_ID);
      workout.name = existing?.name ?? 'City2Surf 2026';
      workout.notes =
        existing?.notes ??
        'Sample workout: Sydney City2Surf, Hyde Park to Bondi Beach via Heartbreak Hill, averaging 6:18 /km, with heart rate. Generated by Locale from the course map; not a real recording.';
      await saveWorkout(workout, track, text);
    }
    await Preferences.set({ key: FLAG_V1, value: '1' });
    await Preferences.set({ key: FLAG_V2, value: '1' });
    return true;
  } catch (e) {
    console.error('Seeding sample workouts failed', e);
    return false;
  }
}
